Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-024e6efaf93d85776
      Tags:
        - Key: "Name"
          Value: "change1"
      SecurityGroups:
        - !Ref eprofileSG

  eprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http && ssh from myIP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:  192.168.5.1/32
 